version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  manage_db:
    build: .
    tty: true
    depends_on:
      - db
    volumes:
      - ./dbschema:/app/dbschema
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:root@db/perfectfit
      - TEST_USER_ID=41482
 
