"""empty message

Revision ID: 031b95ec17e4
Revises: eedf849a69b5
Create Date: 2023-07-10 13:06:03.545984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031b95ec17e4'
down_revision = 'eedf849a69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'location')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
