"""empty message

Revision ID: 0c2631c2b585
Revises: 24514f0577b2
Create Date: 2022-05-24 15:47:34.693045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2631c2b585'
down_revision = '24514f0577b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_activity',
    sa.Column('intervention_activity_id', sa.Integer(), nullable=False),
    sa.Column('intervention_activity_title', sa.String(length=100), nullable=True),
    sa.Column('intervention_activity_description', sa.String(), nullable=True),
    sa.Column('intervention_activity_full_instructions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('intervention_activity_id')
    )
    op.create_table('first_aid_kit',
    sa.Column('first_aid_kit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_activity_id', sa.Integer(), nullable=True),
    sa.Column('user_activity_title', sa.String(length=100), nullable=True),
    sa.Column('user_activity_description', sa.String(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intervention_activity_id'], ['intervention_activity.intervention_activity_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('first_aid_kit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('first_aid_kit')
    op.drop_table('intervention_activity')
    # ### end Alembic commands ###
