"""empty message

Revision ID: 1adcbea42a95
Revises: 95bcf99801ec
Create Date: 2023-05-09 13:15:45.510605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adcbea42a95'
down_revision = '95bcf99801ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pa_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pa_group')
    # ### end Alembic commands ###
