"""empty message

Revision ID: 213ef004b216
Revises: c55d12b493cf
Create Date: 2022-03-10 08:38:07.820515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213ef004b216'
down_revision = 'c55d12b493cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intervention_state', sa.Column('futureselfdialogstep', sa.String(), nullable=True))
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_intervention_state', 'futureselfdialogpart')
    op.drop_column('user_intervention_state', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intervention_state', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('user_intervention_state', sa.Column('futureselfdialogpart', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_intervention_state', 'futureselfdialogstep')
    # ### end Alembic commands ###
