"""empty message

Revision ID: 24514f0577b2
Revises: 
Create Date: 2022-04-04 20:11:39.403927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24514f0577b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('users',
    sa.Column('nicedayuid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('nicedayuid')
    )
    op.create_table('closed_user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialog_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('user_intervention_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_component', sa.String(), nullable=True),
    sa.Column('last_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_part', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_intervention_state')
    op.drop_table('dialog_answers')
    op.drop_table('closed_user_answers')
    op.drop_table('users')
    op.drop_table('dialog_questions')
    # ### end Alembic commands ###
