"""empty message

Revision ID: 2cf4a55505b7
Revises: ae8f001503c6
Create Date: 2023-02-09 08:24:52.874807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf4a55505b7'
down_revision = 'ae8f001503c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quit_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('long_term_pa_goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'long_term_pa_goal')
    op.drop_column('users', 'quit_date')
    # ### end Alembic commands ###
