"""empty message

Revision ID: 2de63993d94e
Revises: 
Create Date: 2022-07-15 14:31:26.464737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de63993d94e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('intervention_activity',
    sa.Column('intervention_activity_id', sa.Integer(), nullable=False),
    sa.Column('intervention_activity_title', sa.String(length=100), nullable=True),
    sa.Column('intervention_activity_description', sa.String(), nullable=True),
    sa.Column('intervention_activity_full_instructions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('intervention_activity_id')
    )
    op.create_table('intervention_components',
    sa.Column('intervention_component_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_component_name', sa.String(length=100), nullable=True),
    sa.Column('intervention_component_trigger', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('intervention_component_id')
    )
    op.create_table('intervention_phases',
    sa.Column('phase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('phase_id')
    )
    op.create_table('users',
    sa.Column('nicedayuid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('nicedayuid')
    )
    op.create_table('dialog_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('first_aid_kit',
    sa.Column('first_aid_kit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_activity_id', sa.Integer(), nullable=True),
    sa.Column('user_activity_title', sa.String(length=100), nullable=True),
    sa.Column('user_activity_description', sa.String(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intervention_activity_id'], ['intervention_activity.intervention_activity_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('first_aid_kit_id')
    )
    op.create_table('user_intervention_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_phase_id', sa.Integer(), nullable=True),
    sa.Column('intervention_component_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_part', sa.Integer(), nullable=True),
    sa.Column('next_planned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['intervention_component_id'], ['intervention_components.intervention_component_id'], ),
    sa.ForeignKeyConstraint(['intervention_phase_id'], ['intervention_phases.phase_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_preferences_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_component_id', sa.Integer(), nullable=True),
    sa.Column('recursive', sa.Boolean(), nullable=True),
    sa.Column('week_days', sa.String(length=13), nullable=True),
    sa.Column('preferred_time', sa.Time(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intervention_component_id'], ['intervention_components.intervention_component_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('user_preferences_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('user_intervention_state')
    op.drop_table('first_aid_kit')
    op.drop_table('dialog_answers')
    op.drop_table('users')
    op.drop_table('intervention_phases')
    op.drop_table('intervention_components')
    op.drop_table('intervention_activity')
    op.drop_table('dialog_questions')
    # ### end Alembic commands ###
