"""empty message

Revision ID: 371db19fa5b8
Revises: c7af1944414c
Create Date: 2023-01-18 08:29:48.255813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371db19fa5b8'
down_revision = 'c7af1944414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testim_godin_activity_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('testim_running_walking_pref', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('testim_self_efficacy_pref', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('testim_sim_cluster_1', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('testim_sim_cluster_3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testim_sim_cluster_3')
    op.drop_column('users', 'testim_sim_cluster_1')
    op.drop_column('users', 'testim_self_efficacy_pref')
    op.drop_column('users', 'testim_running_walking_pref')
    op.drop_column('users', 'testim_godin_activity_level')
    # ### end Alembic commands ###
