"""empty message

Revision ID: 39447dff8c4d
Revises: 110b1e4ad85f
Create Date: 2021-09-09 14:13:03.662851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39447dff8c4d'
down_revision = '110b1e4ad85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
