"""empty message

Revision ID: 40b1f3c12eab
Revises: c7af1944414c
Create Date: 2022-12-09 13:08:56.107009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b1f3c12eab'
down_revision = 'c7af1944414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
