"""empty message

Revision ID: 4c76d5098610
Revises: aa642a5f2f2d
Create Date: 2022-03-07 14:57:18.604984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c76d5098610'
down_revision = 'aa642a5f2f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('dialog_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog_answers')
    op.drop_table('dialog_questions')
    # ### end Alembic commands ###
