"""empty message

Revision ID: 564c662a5428
Revises: e563082c2ef6
Create Date: 2022-11-09 15:29:36.791368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c662a5428'
down_revision = 'e563082c2ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_activities_performed',
    sa.Column('intervention_activities_performed_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_activity_id', sa.Integer(), nullable=True),
    sa.Column('completed_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intervention_activity_id'], ['intervention_activity.intervention_activity_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('intervention_activities_performed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_activities_performed')
    # ### end Alembic commands ###
