"""empty message

Revision ID: 60961c3277e7
Revises: f71b9142e0f3
Create Date: 2022-03-10 17:31:12.229824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60961c3277e7'
down_revision = 'f71b9142e0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
