"""empty message

Revision ID: 65e13e9d7c97
Revises: 5d5f35b7bf23
Create Date: 2023-05-09 13:24:39.471185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e13e9d7c97'
down_revision = '5d5f35b7bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pa_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pa_group')
    # ### end Alembic commands ###
