"""empty message

Revision ID: 6deeec60f2bb
Revises: 5d5f35b7bf23
Create Date: 2023-05-10 14:56:24.571183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6deeec60f2bb'
down_revision = '5d5f35b7bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pa_steps_daily_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_intensity_minutes_weekly_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_intervention_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pa_intervention_group')
    op.drop_column('users', 'pa_intensity_minutes_weekly_goal')
    op.drop_column('users', 'pa_steps_daily_goal')
    # ### end Alembic commands ###
