"""empty message

Revision ID: 77920fa60697
Revises: e69e5ba8a53b
Create Date: 2022-03-14 19:15:28.620575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77920fa60697'
down_revision = 'e69e5ba8a53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
