"""empty message

Revision ID: 88098224b348
Revises: 24514f0577b2
Create Date: 2022-05-23 14:35:01.239212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88098224b348'
down_revision = '24514f0577b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_aid_kit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('activity_description', sa.String(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('first_aid_kit')
    # ### end Alembic commands ###
