"""empty message

Revision ID: 8faa75d69b6b
Revises: 110dd0402c8e
Create Date: 2022-03-30 09:35:20.054969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8faa75d69b6b'
down_revision = '110dd0402c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('dialog_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog_answers')
    op.drop_table('dialog_questions')
    # ### end Alembic commands ###
