"""empty message

Revision ID: 92e3019a3761
Revises: 24514f0577b2
Create Date: 2022-05-11 13:16:12.531850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e3019a3761'
down_revision = '24514f0577b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closed_user_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_user_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], name='closed_user_answers_users_nicedayuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='closed_user_answers_pkey')
    )
    # ### end Alembic commands ###
