"""empty message

Revision ID: 986bd1795e07
Revises: 12a122ccf8e6
Create Date: 2022-11-14 14:22:19.040775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986bd1795e07'
down_revision = '12a122ccf8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention_activity', sa.Column('user_input', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention_activity', 'user_input')
    # ### end Alembic commands ###
