"""empty message

Revision ID: 9c89259ea4f1
Revises: 28f7d1051652
Create Date: 2023-02-04 07:18:52.358528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c89259ea4f1'
down_revision = '28f7d1051652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_counts',
    sa.Column('step_count_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('step_count_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_counts')
    # ### end Alembic commands ###
