"""empty message

Revision ID: a72e609148ed
Revises: ee3f50c880d1
Create Date: 2022-03-10 16:08:39.019144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72e609148ed'
down_revision = 'ee3f50c880d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
