"""empty message

Revision ID: a8e01f44459c
Revises: 5d5f35b7bf23
Create Date: 2023-05-10 13:40:06.939321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e01f44459c'
down_revision = '5d5f35b7bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pa_group', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_intensity_minutes_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weekly_steps_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_steps_goal')
    op.drop_column('users', 'pa_intensity_minutes_goal')
    op.drop_column('users', 'pa_group')
    # ### end Alembic commands ###
