"""empty message

Revision ID: be09a2476838
Revises: e8be58ef0e09
Create Date: 2023-03-15 10:30:32.568014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be09a2476838'
down_revision = 'e8be58ef0e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_preferences_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_component_id', sa.Integer(), nullable=True),
    sa.Column('recursive', sa.Boolean(), nullable=True),
    sa.Column('week_days', sa.String(length=13), nullable=True),
    sa.Column('preferred_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intervention_component_id'], ['intervention_components.intervention_component_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('user_preferences_id')
    )
    op.create_table('user_state_machine',
    sa.Column('state_machine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('dialog_running', sa.Boolean(), nullable=True),
    sa.Column('dialog_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intervention_component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_component_id'], ['intervention_components.intervention_component_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('state_machine_id')
    )
    op.add_column('users', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('execution_week', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_steps_daily_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_intensity_minutes_weekly_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pa_intervention_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pa_intervention_group')
    op.drop_column('users', 'pa_intensity_minutes_weekly_goal')
    op.drop_column('users', 'pa_steps_daily_goal')
    op.drop_column('users', 'execution_week')
    op.drop_column('users', 'start_date')
    op.drop_table('user_state_machine')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
