"""empty message

Revision ID: be53ab5e40fa
Revises: c7af1944414c
Create Date: 2023-01-18 14:53:39.429539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be53ab5e40fa'
down_revision = 'c7af1944414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('testimonial_id', sa.Integer(), nullable=False),
    sa.Column('godin_activity_level', sa.Integer(), nullable=True),
    sa.Column('running_walking_pref', sa.Integer(), nullable=True),
    sa.Column('self_efficacy_pref', sa.Float(), nullable=True),
    sa.Column('testimonial_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('testimonial_id')
    )
    op.add_column('users', sa.Column('testim_godin_activity_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('testim_running_walking_pref', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('testim_self_efficacy_pref', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('testim_sim_cluster_1', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('testim_sim_cluster_3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testim_sim_cluster_3')
    op.drop_column('users', 'testim_sim_cluster_1')
    op.drop_column('users', 'testim_self_efficacy_pref')
    op.drop_column('users', 'testim_running_walking_pref')
    op.drop_column('users', 'testim_godin_activity_level')
    op.drop_table('testimonials')
    # ### end Alembic commands ###
