"""empty message

Revision ID: c374e98086d3
Revises: 564c662a5428
Create Date: 2022-11-09 15:31:56.970583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c374e98086d3'
down_revision = '564c662a5428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
