"""empty message

Revision ID: ca3171329c7b
Revises: 213ef004b216
Create Date: 2022-03-10 13:26:44.130055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3171329c7b'
down_revision = '213ef004b216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
