"""empty message

Revision ID: d310d6ff2cf4
Revises: 7a9917098603
Create Date: 2023-02-23 09:18:17.389723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd310d6ff2cf4'
down_revision = '7a9917098603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('execution_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'execution_week')
    op.drop_column('users', 'start_date')
    # ### end Alembic commands ###
