"""empty message

Revision ID: dcd3663ba17d
Revises: 258f980de9f2
Create Date: 2022-12-05 08:45:44.942657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcd3663ba17d'
down_revision = '258f980de9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_answers',
    sa.Column('closed_answers_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_value', sa.Integer(), nullable=True),
    sa.Column('answer_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.PrimaryKeyConstraint('closed_answers_id')
    )
    op.create_table('dialog_open_answers',
    sa.Column('dialog_open_answers_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_value', sa.String(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('dialog_open_answers_id')
    )
    op.create_table('dialog_closed_answers',
    sa.Column('dialog_closed_answers_id', sa.Integer(), nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('closed_answers_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_answers_id'], ['closed_answers.closed_answers_id'], ),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('dialog_closed_answers_id')
    )
    op.drop_table('dialog_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_answers',
    sa.Column('answer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dialog_questions.question_id'], name='dialog_answers_question_id_fkey'),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], name='dialog_answers_users_nicedayuid_fkey'),
    sa.PrimaryKeyConstraint('answer_id', name='dialog_answers_pkey')
    )
    op.drop_table('dialog_closed_answers')
    op.drop_table('dialog_open_answers')
    op.drop_table('closed_answers')
    # ### end Alembic commands ###
