"""empty message

Revision ID: e69e5ba8a53b
Revises: aa642a5f2f2d
Create Date: 2022-03-14 11:18:26.664120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69e5ba8a53b'
down_revision = 'aa642a5f2f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_intervention_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.Integer(), nullable=True),
    sa.Column('intervention_component', sa.String(), nullable=True),
    sa.Column('last_time', sa.DateTime(), nullable=True),
    sa.Column('last_part', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_intervention_state')
    # ### end Alembic commands ###
