"""empty message

Revision ID: ee3f50c880d1
Revises: ca3171329c7b
Create Date: 2022-03-10 16:03:36.773016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee3f50c880d1'
down_revision = 'ca3171329c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intervention_state', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_intervention_state', sa.Column('intervention_component', sa.String(), nullable=True))
    op.add_column('user_intervention_state', sa.Column('last_time', sa.DateTime(), nullable=True))
    op.add_column('user_intervention_state', sa.Column('last_part', sa.String(), nullable=True))
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_intervention_state', 'futureselfdialogdatetime')
    op.drop_column('user_intervention_state', 'futureselfdialogstep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intervention_state', sa.Column('futureselfdialogstep', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_intervention_state', sa.Column('futureselfdialogdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_intervention_state', 'last_part')
    op.drop_column('user_intervention_state', 'last_time')
    op.drop_column('user_intervention_state', 'intervention_component')
    op.drop_column('user_intervention_state', 'id')
    # ### end Alembic commands ###
