"""empty message

Revision ID: eedf849a69b5
Revises: 6deeec60f2bb
Create Date: 2023-06-12 08:11:05.181512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedf849a69b5'
down_revision = '6deeec60f2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
