"""empty message

Revision ID: f06f67b4543c
Revises: 7a9917098603
Create Date: 2023-03-08 08:18:59.270646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06f67b4543c'
down_revision = '7a9917098603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pf_evaluation_grade', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pf_evaluation_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pf_evaluation_comment')
    op.drop_column('users', 'pf_evaluation_grade')
    # ### end Alembic commands ###
