"""empty message

Revision ID: f71b9142e0f3
Revises: e62bd5cd0b81
Create Date: 2022-03-10 17:00:50.870567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71b9142e0f3'
down_revision = 'e62bd5cd0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intervention_state', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_intervention_state', 'intervention_component',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_intervention_state', 'intervention_component',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_intervention_state', 'users_nicedayuid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_intervention_state', 'id')
    # ### end Alembic commands ###
