"""empty message

Revision ID: f7b1056bef09
Revises: f06f67b4543c
Create Date: 2023-03-09 09:53:33.996301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7b1056bef09'
down_revision = 'f06f67b4543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.add_column('users', sa.Column('participant_code', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('week_days', sa.String(length=13), nullable=True))
    op.add_column('users', sa.Column('preferred_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_time')
    op.drop_column('users', 'week_days')
    op.drop_column('users', 'participant_code')
    op.create_table('user_preferences',
    sa.Column('user_preferences_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_nicedayuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intervention_component_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recursive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('week_days', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('preferred_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['intervention_component_id'], ['intervention_components.intervention_component_id'], name='user_preferences_intervention_component_id_fkey'),
    sa.ForeignKeyConstraint(['users_nicedayuid'], ['users.nicedayuid'], name='user_preferences_users_nicedayuid_fkey'),
    sa.PrimaryKeyConstraint('user_preferences_id', name='user_preferences_pkey')
    )
    # ### end Alembic commands ###
